e1000e: checkpatch error - macro panethesis
commit f0f1a172b2a9e26319b9aa95fa6c322ebb01089d upstream.

ERROR: Macros with complex values should be enclosed in parenthesis

Signed-off-by: Bruce Allan <bruce.w.allan@intel.com>
Tested-by: Emil Tantilov <emil.s.tantilov@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>