e1000e: checkpatch error - trailing statements
commit 184125a389cf2c81980de5d5f365c786cc76d229 upstream.

ERROR: trailing statements should be on next line

Signed-off-by: Bruce Allan <bruce.w.allan@intel.com>
Tested-by: Emil Tantilov <emil.s.tantilov@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>